data_dir: "/data/baryal/coastal_mapping/original_fx_res_1.0_v3"
run_name: 'c_custom'
filename: 'lvl25.png'
model_opts:
  args: 
    inchannels: 3
    outchannels: 2
    net_depth: 4
    dropout: 0.3
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0005
window_size: [512, 512]