data_dir: "/data/alex/original_torch"
class_name: "Fornix"
batch_size: 8
run_name: "alex_testing"
epochs: 201
save_every: None
use_channels: [0,1,2]
loss_opts:
  name: "custom"
  masked: True
  weights: [0.2, 0.8]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 3
    outchannels: 2
    net_depth: 4
    dropout: 0.2
    spatial: True
    first_channel_output: 16
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["Greymatter", "Fornix"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
reg_opts:
  l1_reg: 0.00001