device: 0 #cuda 0 1 2 3 cpu
data_dir: "/data/alex/original_torch" #'/data/alex/PHAL' #
class_name: "Fornix" #"PHAL"
batch_size: 8
run_name: "fx" #"PHAL_3"
epochs: 151
save_every: None
use_channels: [0,1,2]
loss_opts:
  name: "unified"
  masked: True
  weights: [0.2, 0.8]
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 3
    outchannels: 2
    net_depth: 4
    dropout: 0.2
    spatial: True
    first_channel_output: 16
    output_act: 'softmax' #works with 'softmax' and 'sigmoid' and None
    architecture: 'unet' #works with 'unet' and 'manet'
optim_opts:
  name: "Adam"
  args:
    lr: 0.0001
log_opts:
  mask_names: ["Background", "Brain Region"]
metrics_opts: ["IoU", "precision", "recall"]
grad_accumulation_steps: None
fine_tune: False
#reg_opts:
#  l1_reg: 0.00001